// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TESTE01CriarPostTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tESTE01CriarPost() {
    driver.get("http://localhost:8080/criaPost");
    {
      List<WebElement> elements = driver.findElements(By.name("id"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.name("titulo"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("textarea"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.name("data"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.name("tag"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#divbut > #botao"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("#divbut > #botao")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("popup"));
      assert(elements.size() == 0);
    }
    driver.findElement(By.name("id")).sendKeys("123");
    driver.findElement(By.name("titulo")).sendKeys("titulo");
    driver.findElement(By.cssSelector("textarea")).sendKeys("texto de exemplo");
    driver.findElement(By.name("data")).click();
    driver.findElement(By.name("data")).sendKeys("2021-03-12");
    driver.findElement(By.name("tag")).sendKeys("teste");
    driver.findElement(By.cssSelector("#divbut > #botao")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("popup"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#popup > img"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("#popup > p")).getText(), is("Enviado com sucesso!"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#popup > #botao"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("#popup > #botao")).click();
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    {
      List<WebElement> elements = driver.findElements(By.id("tabelaPosts"));
      assert(elements.size() > 0);
    }
  }
}
