// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TESTE04AdicionarEmailTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tESTE04AdicionarEmail() {
    driver.get("http://localhost:8080/cadastrarEmail");
    {
      List<WebElement> elements = driver.findElements(By.name("email"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.id("botao"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("botao")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("popup"));
      assert(elements.size() == 0);
    }
    driver.findElement(By.name("nome")).click();
    driver.findElement(By.name("nome")).sendKeys("Antonio");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("antonio@antonio.com.br");
    driver.findElement(By.id("botao")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("popup"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#popup > img"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("p"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#popup > #botao"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("#popup > #botao")).click();
    {
      String value = driver.findElement(By.name("nome")).getAttribute("value");
      assertThat(value, is(""));
    }
    {
      String value = driver.findElement(By.name("email")).getAttribute("value");
      assertThat(value, is(""));
    }
  }
}
